-- AUTHOR: NGUYEN VAN VU
-- TESTING_SYSTEM_ASSIGNMENT_1

DROP DATABASE IF EXISTS `TESTING_SYSTEM_ASSIGNMENT_1`;
CREATE DATABASE `TESTING_SYSTEM_ASSIGNMENT_1`;
USE `TESTING_SYSTEM_ASSIGNMENT_1`;
CREATE TABLE DEPARTMENT (
   DEPARTMENTID INT,
   DEPARTMENTNAME VARCHAR(50)
);

CREATE TABLE   POSITION (
   POSITIONID INT,
   POSITIONNAME VARCHAR(50)
);

CREATE TABLE  ACCOUNT(
   ACCOUNTID INT,
   EMAIL VARCHAR(10),
   USERNAME VARCHAR(10),
   FULLNAME VARCHAR(10),
   DEPARTMENTID INT,
   POSITIONID INT,
   CREATEDATE DATE
   );
   
   CREATE TABLE `GROUP`(
	GROUPID INT,
	GROUPNAME VARCHAR(50),
	CREATORID INT,
	CREATEDATE DATE
	);

CREATE TABLE GROUPACCOUNT(
	GROUPID INT,
    ACCOUNTID INT,
    JOINDATE DATE
);

CREATE TABLE  `TYPEQUESTION`(
	TYPEID INT,
    TYPENAME VARCHAR(10)
);

CREATE TABLE `CATEGORYQUESTION`(
	CATEGORYID INT,
    CATEGORYNAME VARCHAR(20)
);

CREATE TABLE QUESTION(
	QUESTIONID INT,
    CONTENT VARCHAR(50),
    CATEGORYID INT,
    TYPEID INT,
    CREATORID INT,
    CREATEDATE DATE
);

CREATE TABLE `ANSWER`(
	ANSWERID INT,
    CONTENT VARCHAR(50),
    QUESTIONID INT,
    ISCORRECT VARCHAR(10)
);

CREATE TABLE `EXAM`(
	EXAMID INT,
    CODE VARCHAR(20),
    TITLE VARCHAR(10),
    CATEGORYID INT,
    DURATION INT,
    CREATORID INT,
    CREATEDATE DATE
);

CREATE TABLE EXAMQUESTION(
	EXAMID INT,
    QUESTIONIDN INT
);